name: Execute Snowflake Queries

on:
  #push:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'Analytics/Tables/**'
      - 'Analytics/Views/**'
      - 'Analytics/Procedures/**'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  run-snowflake-queries:
    runs-on: ubuntu-latest
    #environment: testing_env

    env:
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_ROLE: ${{ secrets.SF_ROLE }}
      SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
      SF_DATABASE: ${{ secrets.SF_DATABASE }}
      SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
      SF_PASSWORD: ${{ secrets.SF_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SnowSQL
      run: |
        curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
        SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

    - name: Configure SnowSQL
      run: |
        mkdir -p ~/.snowsql/
        echo '[connections]' > ~/.snowsql/config
        echo "accountname = ${SF_ACCOUNT}" >> ~/.snowsql/config
        echo "username = ${SF_USERNAME}" >> ~/.snowsql/config
        echo "password = \"${SF_PASSWORD}\"" >> ~/.snowsql/config
        echo "warehousename = ${SF_WAREHOUSE}" >> ~/.snowsql/config
        echo "databasename = ${SF_DATABASE}" >> ~/.snowsql/config
        echo "schemaname = ${SF_SCHEMA}" >> ~/.snowsql/config
        echo "rolename = ${SF_ROLE}" >> ~/.snowsql/config
        chmod 700 ~/.snowsql/config
        cat ~/.snowsql/config
        env
        SNOWSQL_CONFIG_FILE=~/.snowsql/config ~/bin/snowsql -o log_level=DEBUG

    - name: Use Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-connector-python

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40

    - name: Execute SQL Queries
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # Check if the file matches the paths to be ignored
          if echo "$file" | grep -E '(\.github|Analytics/Tables)'; then
            echo "Skipping file: $file"
          else
            echo "Processing file: $file"
            if [ -f "$file" ]; then
              ~/bin/snowsql -f "$file"
            else
              echo "File not found: $file"
            fi
          fi
        done
