name: Execute Snowflake Queries

on:
  push:
    branches:
      - main
    paths:
      - 'sql_files/**'

  #Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  run-snowflake-queries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Python 3.12.x
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.12.x

    - name: Run schemachange
      env:
        SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_ROLE: ${{ secrets.SF_ROLE }}
        SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SF_DATABASE: ${{ secrets.SF_DATABASE }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      run:
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        python --version
        echo "step 1: Installing schemachange"
        pip install schemachange


        echo "Step 2: Running schemachange"
        scehmachange -f $GITHUB_WORKSPACE/sql_files -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY 
        








      
